### ISSUE TITLE
TypeError: Cannot read property 'method' of undefined  tracker-stream.js:34:3

### ISSUE THREAD

**Issue by westtrade** [npm/are-we-there-yet#97]
```sh
> iltorb@2.4.1 install /node_modules/iltorb
> node ./scripts/install.js || node-gyp rebuild

/node_modules/are-we-there-yet/tracker-stream.js:34
  .method('completed')
  ^

TypeError: Cannot read property 'method' of undefined
    at Object.<anonymous> (/node_modules/are-we-there-yet/tracker-stream.js:34:3)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/node_modules/are-we-there-yet/tracker-group.js:5:21)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
```

Node version: v11.4.0

**Comment by SevanandYadav** [comment]
Getting Issue:
The First time i installed the npm managed application it worked fine . but next time installed on the machine it shows following Error:

Installing packages...
util.js:160
throw new ('superCtor.prototype',
^
TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor.prototype" property must be of type object. Received undefined
at Object.inherits (util.js:160:11)
at Object. (C:\Program Files\nodejs\node_modules\npm\node_modules\are-we-there-yet\node_modules\readable-stream\lib_stream_duplex.js:53:6)
at Module._compile (internal/modules/cjs/loader.js:1138:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
at Module.load (internal/modules/cjs/loader.js:986:32)
at Function.Module._load (internal/modules/cjs/loader.js:879:14)
at Module.require (internal/modules/cjs/loader.js:1026:19)
at require (internal/modules/cjs/helpers.js:72:18)
at Object. (C:\Program Files\nodejs\node_modules\npm\node_modules\are-we-there-yet\node_modules\readable-stream\readable.js:16:20)
at Module._compile (internal/modules/cjs/loader.js:1138:30) {
code: 'ERR_INVALID_ARG_TYPE'
}

Tried removing loader.js but issue still persists.
Please Suggest resolution
